[package]
name = "npu-to-fhir"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.8.1"
fhir-sdk = "0.14.1"
serde_json = "1.0.140"
clap = { version = "4.5", features = ["derive"] }
time = { version = "0.3", features = ["macros"] }